<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\ServiceCategory;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        // Get service categories if they exist, otherwise use null
        $webDev = ServiceCategory::where('name', 'Web Development')->first();
        $marketing = ServiceCategory::where('name', 'Digital Marketing')->first();
        $consulting = ServiceCategory::where('name', 'Business Consulting')->first();
        $design = ServiceCategory::where('name', 'Graphic Design')->first();
        $itSupport = ServiceCategory::where('name', 'IT Support')->first();
        $content = ServiceCategory::where('name', 'Content Creation')->first();

        $products = [
            // Web Development Services
            [
                'id' => Str::uuid(),
                'name' => 'Custom Website Development',
                'code' => 'WEB-001',
                'description' => 'Full custom website development with responsive design, CMS integration, and SEO optimization',
                'category_id' => $webDev?->id,
                'unit_price' => 2500.00,
                'cost_price' => 1500.00,
                'currency' => 'USD',
                'service_type' => 'one_time',
                'billing_cycle' => null,
                'estimated_hours' => 40.0,
                'service_duration_days' => 30,
                'setup_fee' => 200.00,
                'track_inventory' => false,
                'stock_quantity' => 0,
                'low_stock_threshold' => 0,
                'has_tiered_pricing' => false,
                'pricing_tiers' => null,
                'required_skills' => json_encode(['HTML', 'CSS', 'JavaScript', 'PHP', 'Laravel']),
                'complexity_level' => 3,
                'prerequisites' => 'Client must provide content and branding guidelines',
                'is_taxable' => true,
                'tax_category' => 'digital_services',
                'is_active' => true,
            ],
            [
                'id' => Str::uuid(),
                'name' => 'E-commerce Website',
                'code' => 'WEB-002',
                'description' => 'Complete e-commerce solution with payment integration, inventory management, and admin panel',
                'category_id' => $webDev?->id,
                'unit_price' => 4500.00,
                'cost_price' => 2800.00,
                'currency' => 'USD',
                'service_type' => 'one_time',
                'billing_cycle' => null,
                'estimated_hours' => 80.0,
                'service_duration_days' => 60,
                'setup_fee' => 500.00,
                'track_inventory' => false,
                'stock_quantity' => 0,
                'low_stock_threshold' => 0,
                'has_tiered_pricing' => true,
                'pricing_tiers' => json_encode([
                    ['min_quantity' => 1, 'max_quantity' => 1, 'price' => 4500.00],
                    ['min_quantity' => 2, 'max_quantity' => null, 'price' => 4000.00] // Discount for multiple sites
                ]),
                'required_skills' => json_encode(['Laravel', 'Vue.js', 'Payment APIs', 'Database Design']),
                'complexity_level' => 4,
                'prerequisites' => 'Product catalog, payment gateway accounts, hosting environment',
                'is_taxable' => true,
                'tax_category' => 'digital_services',
                'is_active' => true,
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Website Maintenance',
                'code' => 'WEB-003',
                'description' => 'Monthly website maintenance, security updates, backups, and content updates',
                'category_id' => $webDev?->id,
                'unit_price' => 150.00,
                'cost_price' => 80.00,
                'currency' => 'USD',
                'service_type' => 'recurring',
                'billing_cycle' => 'monthly',
                'estimated_hours' => 4.0,
                'service_duration_days' => 30,
                'setup_fee' => 0.00,
                'track_inventory' => false,
                'stock_quantity' => 0,
                'low_stock_threshold' => 0,
                'has_tiered_pricing' => true,
                'pricing_tiers' => json_encode([
                    ['min_months' => 1, 'max_months' => 11, 'price' => 150.00],
                    ['min_months' => 12, 'max_months' => null, 'price' => 130.00] // Annual discount
                ]),
                'required_skills' => json_encode(['WordPress', 'Server Management', 'Security']),
                'complexity_level' => 2,
                'prerequisites' => 'Existing website and hosting access',
                'is_taxable' => true,
                'tax_category' => 'digital_services',
                'is_active' => true,
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Landing Page Design',
                'code' => 'WEB-004',
                'description' => 'High-converting landing page design and development with A/B testing setup',
                'category_id' => $webDev?->id,
                'unit_price' => 800.00,
                'cost_price' => 500.00,
                'currency' => 'USD',
                'service_type' => 'one_time',
                'billing_cycle' => null,
                'estimated_hours' => 16.0,
                'service_duration_days' => 14,
                'setup_fee' => 0.00,
                'track_inventory' => false,
                'stock_quantity' => 0,
                'low_stock_threshold' => 0,
                'has_tiered_pricing' => false,
                'pricing_tiers' => null,
                'required_skills' => json_encode(['HTML', 'CSS', 'JavaScript', 'Conversion Optimization']),
                'complexity_level' => 2,
                'prerequisites' => 'Marketing copy and brand assets',
                'is_taxable' => true,
                'tax_category' => 'digital_services',
                'is_active' => true,
            ],

            // Digital Marketing Services
            [
                'id' => Str::uuid(),
                'name' => 'SEO Optimization Package',
                'code' => 'MKT-001',
                'description' => 'Complete SEO audit, keyword research, on-page optimization, and technical SEO improvements',
                'category_id' => $marketing?->id,
                'unit_price' => 1200.00,
                'cost_price' => 600.00,
                'currency' => 'USD',
                'service_type' => 'one_time',
                'billing_cycle' => null,
                'estimated_hours' => 24.0,
                'service_duration_days' => 30,
                'setup_fee' => 0.00,
                'track_inventory' => false,
                'stock_quantity' => 0,
                'low_stock_threshold' => 0,
                'has_tiered_pricing' => false,
                'pricing_tiers' => null,
                'required_skills' => json_encode(['SEO', 'Analytics', 'Content Strategy', 'Technical SEO']),
                'complexity_level' => 3,
                'prerequisites' => 'Website access and Google Analytics setup',
                'is_taxable' => true,
                'tax_category' => 'digital_services',
                'is_active' => true,
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Google Ads Management',
                'code' => 'MKT-002',
                'description' => 'Monthly Google Ads campaign management, optimization, and reporting',
                'category_id' => $marketing?->id,
                'unit_price' => 500.00,
                'cost_price' => 250.00,
                'currency' => 'USD',
                'service_type' => 'recurring',
                'billing_cycle' => 'monthly',
                'estimated_hours' => 8.0,
                'service_duration_days' => 30,
                'setup_fee' => 300.00,
                'track_inventory' => false,
                'stock_quantity' => 0,
                'low_stock_threshold' => 0,
                'has_tiered_pricing' => true,
                'pricing_tiers' => json_encode([
                    ['ad_spend' => 1000, 'price' => 500.00],
                    ['ad_spend' => 5000, 'price' => 750.00],
                    ['ad_spend' => 10000, 'price' => 1000.00]
                ]),
                'required_skills' => json_encode(['Google Ads', 'PPC', 'Analytics', 'Conversion Tracking']),
                'complexity_level' => 3,
                'prerequisites' => 'Google Ads account and conversion tracking setup',
                'is_taxable' => true,
                'tax_category' => 'digital_services',
                'is_active' => true,
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Social Media Marketing',
                'code' => 'MKT-003',
                'description' => 'Social media strategy, content creation, posting, and community management',
                'category_id' => $marketing?->id,
                'unit_price' => 750.00,
                'cost_price' => 400.00,
                'currency' => 'USD',
                'service_type' => 'recurring',
                'billing_cycle' => 'monthly',
                'estimated_hours' => 12.0,
                'service_duration_days' => 30,
                'setup_fee' => 200.00,
                'track_inventory' => false,
                'stock_quantity' => 0,
                'low_stock_threshold' => 0,
                'has_tiered_pricing' => true,
                'pricing_tiers' => json_encode([
                    ['platforms' => 2, 'price' => 750.00],
                    ['platforms' => 4, 'price' => 1200.00],
                    ['platforms' => 6, 'price' => 1800.00]
                ]),
                'required_skills' => json_encode(['Social Media', 'Content Creation', 'Community Management']),
                'complexity_level' => 2,
                'prerequisites' => 'Social media account access and brand guidelines',
                'is_taxable' => true,
                'tax_category' => 'digital_services',
                'is_active' => true,
            ],

            // Business Consulting
            [
                'id' => Str::uuid(),
                'name' => 'Business Strategy Consulting',
                'code' => 'CON-001',
                'description' => 'Strategic planning, business analysis, and growth strategy development',
                'category_id' => $consulting?->id,
                'unit_price' => 150.00,
                'cost_price' => 75.00,
                'currency' => 'USD',
                'service_type' => 'usage_based',
                'billing_cycle' => 'hourly',
                'estimated_hours' => 1.0,
                'service_duration_days' => null,
                'setup_fee' => 0.00,
                'track_inventory' => false,
                'stock_quantity' => 0,
                'low_stock_threshold' => 0,
                'has_tiered_pricing' => true,
                'pricing_tiers' => json_encode([
                    ['min_hours' => 1, 'max_hours' => 9, 'price' => 150.00],
                    ['min_hours' => 10, 'max_hours' => 39, 'price' => 140.00],
                    ['min_hours' => 40, 'max_hours' => null, 'price' => 130.00]
                ]),
                'required_skills' => json_encode(['Strategy', 'Business Analysis', 'Planning', 'Market Research']),
                'complexity_level' => 4,
                'prerequisites' => 'Business overview session and financial data access',
                'is_taxable' => true,
                'tax_category' => 'consulting',
                'is_active' => true,
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Digital Transformation',
                'code' => 'CON-002',
                'description' => 'Complete digital transformation consulting and implementation roadmap',
                'category_id' => $consulting?->id,
                'unit_price' => 5000.00,
                'cost_price' => 3000.00,
                'currency' => 'USD',
                'service_type' => 'one_time',
                'billing_cycle' => null,
                'estimated_hours' => 60.0,
                'service_duration_days' => 90,
                'setup_fee' => 0.00,
                'track_inventory' => false,
                'stock_quantity' => 0,
                'low_stock_threshold' => 0,
                'has_tiered_pricing' => false,
                'pricing_tiers' => null,
                'required_skills' => json_encode(['Digital Strategy', 'Process Optimization', 'Technology Assessment']),
                'complexity_level' => 5,
                'prerequisites' => 'Executive stakeholder commitment and current process documentation',
                'is_taxable' => true,
                'tax_category' => 'consulting',
                'is_active' => true,
            ],

            // Graphic Design
            [
                'id' => Str::uuid(),
                'name' => 'Logo Design Package',
                'code' => 'DES-001',
                'description' => 'Complete logo design with multiple concepts, revisions, and file formats',
                'category_id' => $design?->id,
                'unit_price' => 600.00,
                'cost_price' => 300.00,
                'currency' => 'USD',
                'service_type' => 'one_time',
                'billing_cycle' => null,
                'estimated_hours' => 12.0,
                'service_duration_days' => 14,
                'setup_fee' => 0.00,
                'track_inventory' => false,
                'stock_quantity' => 0,
                'low_stock_threshold' => 0,
                'has_tiered_pricing' => false,
                'pricing_tiers' => null,
                'required_skills' => json_encode(['Adobe Illustrator', 'Branding', 'Typography', 'Color Theory']),
                'complexity_level' => 2,
                'prerequisites' => 'Brand brief and style preferences',
                'is_taxable' => true,
                'tax_category' => 'design_services',
                'is_active' => true,
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Brand Identity Package',
                'code' => 'DES-002',
                'description' => 'Complete brand identity including logo, colors, fonts, and brand guidelines',
                'category_id' => $design?->id,
                'unit_price' => 1500.00,
                'cost_price' => 800.00,
                'currency' => 'USD',
                'service_type' => 'one_time',
                'billing_cycle' => null,
                'estimated_hours' => 30.0,
                'service_duration_days' => 21,
                'setup_fee' => 0.00,
                'track_inventory' => false,
                'stock_quantity' => 0,
                'low_stock_threshold' => 0,
                'has_tiered_pricing' => false,
                'pricing_tiers' => null,
                'required_skills' => json_encode(['Adobe Creative Suite', 'Brand Strategy', 'Design Systems']),
                'complexity_level' => 3,
                'prerequisites' => 'Business strategy session and target audience definition',
                'is_taxable' => true,
                'tax_category' => 'design_services',
                'is_active' => true,
            ],

            // IT Support
            [
                'id' => Str::uuid(),
                'name' => 'IT Support Monthly',
                'code' => 'IT-001',
                'description' => 'Monthly IT support, maintenance, monitoring, and help desk services',
                'category_id' => $itSupport?->id,
                'unit_price' => 300.00,
                'cost_price' => 150.00,
                'currency' => 'USD',
                'service_type' => 'recurring',
                'billing_cycle' => 'monthly',
                'estimated_hours' => 6.0,
                'service_duration_days' => 30,
                'setup_fee' => 150.00,
                'track_inventory' => false,
                'stock_quantity' => 0,
                'low_stock_threshold' => 0,
                'has_tiered_pricing' => true,
                'pricing_tiers' => json_encode([
                    ['users' => 10, 'price' => 300.00],
                    ['users' => 25, 'price' => 650.00],
                    ['users' => 50, 'price' => 1200.00]
                ]),
                'required_skills' => json_encode(['System Administration', 'Network Management', 'Security']),
                'complexity_level' => 2,
                'prerequisites' => 'Network assessment and remote access setup',
                'is_taxable' => true,
                'tax_category' => 'it_services',
                'is_active' => true,
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Server Setup & Configuration',
                'code' => 'IT-002',
                'description' => 'Complete server setup, configuration, security hardening, and documentation',
                'category_id' => $itSupport?->id,
                'unit_price' => 800.00,
                'cost_price' => 400.00,
                'currency' => 'USD',
                'service_type' => 'one_time',
                'billing_cycle' => null,
                'estimated_hours' => 16.0,
                'service_duration_days' => 7,
                'setup_fee' => 0.00,
                'track_inventory' => false,
                'stock_quantity' => 0,
                'low_stock_threshold' => 0,
                'has_tiered_pricing' => false,
                'pricing_tiers' => null,
                'required_skills' => json_encode(['Linux', 'Networking', 'Security', 'Docker']),
                'complexity_level' => 4,
                'prerequisites' => 'Server hardware or cloud hosting account',
                'is_taxable' => true,
                'tax_category' => 'it_services',
                'is_active' => true,
            ],

            // Content Creation
            [
                'id' => Str::uuid(),
                'name' => 'Blog Content Writing',
                'code' => 'CON-001',
                'description' => 'Professional blog post writing with SEO optimization and research',
                'category_id' => $content?->id,
                'unit_price' => 100.00,
                'cost_price' => 50.00,
                'currency' => 'USD',
                'service_type' => 'usage_based',
                'billing_cycle' => 'per_post',
                'estimated_hours' => 3.0,
                'service_duration_days' => 3,
                'setup_fee' => 0.00,
                'track_inventory' => false,
                'stock_quantity' => 0,
                'low_stock_threshold' => 0,
                'has_tiered_pricing' => true,
                'pricing_tiers' => json_encode([
                    ['word_count' => 500, 'price' => 100.00],
                    ['word_count' => 1000, 'price' => 180.00],
                    ['word_count' => 1500, 'price' => 250.00]
                ]),
                'required_skills' => json_encode(['Content Writing', 'SEO', 'Research', 'WordPress']),
                'complexity_level' => 2,
                'prerequisites' => 'Content brief and target keywords',
                'is_taxable' => true,
                'tax_category' => 'content_services',
                'is_active' => true,
            ],
            [
                'id' => Str::uuid(),
                'name' => 'Website Copywriting',
                'code' => 'CON-002',
                'description' => 'Complete website copywriting package including pages, CTAs, and meta descriptions',
                'category_id' => $content?->id,
                'unit_price' => 800.00,
                'cost_price' => 400.00,
                'currency' => 'USD',
                'service_type' => 'one_time',
                'billing_cycle' => null,
                'estimated_hours' => 16.0,
                'service_duration_days' => 10,
                'setup_fee' => 0.00,
                'track_inventory' => false,
                'stock_quantity' => 0,
                'low_stock_threshold' => 0,
                'has_tiered_pricing' => false,
                'pricing_tiers' => null,
                'required_skills' => json_encode(['Copywriting', 'SEO', 'Marketing', 'Brand Voice']),
                'complexity_level' => 3,
                'prerequisites' => 'Brand guidelines and target audience persona',
                'is_taxable' => true,
                'tax_category' => 'content_services',
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }

        $this->command->info('✅ Products seeded successfully - ' . count($products) . ' services created');
        $this->command->info('📦 Product categories:');
        $this->command->info('   - Web Development: 4 services');
        $this->command->info('   - Digital Marketing: 3 services');
        $this->command->info('   - Business Consulting: 2 services');
        $this->command->info('   - Graphic Design: 2 services');
        $this->command->info('   - IT Support: 2 services');
        $this->command->info('   - Content Creation: 2 services');
    }
}